-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : sam. 17 jan. 2026 à 09:35
-- Version du serveur : 10.4.32-MariaDB
-- Version de PHP : 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `dbs12522068`
--

-- --------------------------------------------------------

--
-- Structure de la table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL DEFAULT '0',
  `price` float NOT NULL,
  `description` text NOT NULL,
  `paragraphe` text NOT NULL,
  `url_photo` varchar(255) NOT NULL,
  `categorie` varchar(255) NOT NULL,
  `autre_url_photo` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `products`
--

INSERT INTO `products` (`id`, `name`, `price`, `description`, `paragraphe`, `url_photo`, `categorie`, `autre_url_photo`) VALUES
(1, 'menu fruite', 19.99, 'Menu contenant 10 eliquide de 10ml avec de doux aromes de fruit frais.', '<p class=\'p-eliquide\'> <b> 1. *Fraise Sucrée:</b> Plongez dans une explosion de fraîcheur avec notre e-liquide à la fraise sucrée. Chaque inhalation offre une délicieuse fusion de fraises mûres et de douceur sucrée, créant une expérience fruitée inoubliable. </p> <p class=\'p-eliquide\'> <b> 2. *Orange Citronnée:</b> Réveillez vos papilles avec notre e-liquide à l\'orange citronnée. L\'acidité vive de l\'orange associée à une légère douceur crée un équilibre parfait pour une expérience rafraîchissante à chaque bouffée. </p> <p class=\'p-eliquide\'> <b> 3. *Pomme Croquante:</b> Savourez la fraîcheur croquante de notre e-liquide à la pomme. Chaque inhalation offre la délicatesse sucrée d\'une pomme fraîchement cueillie, pour une vape légère et délicieuse. </p> <p class=\'p-eliquide\'> <b>4. *Baies Sauvages:</b> Découvrez la symphonie des baies sauvages dans notre e-liquide unique. Les saveurs complexes des mûres, des myrtilles et des framboises se mêlent pour créer une expérience fruitée intense. </p> <p class=\'p-eliquide\'> <b> 5. *Cerise Gourmande:</b> Plaisir sucré garanti avec notre e-liquide à la cerise gourmande. Les notes sucrées et acidulées des cerises mûres se marient pour créer une expérience de vape irrésistible. </p> <p class=\'p-eliquide\'> <b> 6. *Raisin Mûr:</b> Goûtez à la sophistication avec notre e-liquide au raisin mûr. Les saveurs riches et sucrées du raisin sont parfaitement équilibrées, offrant une vapeur pleine de délice. </p> <p class=\'p-eliquide\'> <b> 7. *Melon Juteux:</b> Laissez-vous séduire par notre e-liquide au melon juteux. La douceur juteuse du melon est magnifiquement capturée dans chaque bouffée, offrant une expérience rafraîchissante et délicieuse. </p> <p class=\'p-eliquide\'> <b> 8. *Pastèque Rafraîchissante:</b> Rafraîchissez-vous avec notre e-liquide à la pastèque. Chaque bouffée offre la douceur juteuse de la pastèque, parfaite pour une vape légère et estivale. </p> <p class=\'p-eliquide\'> <b> 9. *Pêche Délicate:</b> Plongez dans la douceur avec notre e-liquide à la pêche délicate. Chaque inhalation offre la saveur sucrée et juteuse de la pêche, créant une expérience fruitée légère et plaisante. </p> <p class=\'p-eliquide\'> <b> 10. *Kiwi Exquis:</b> Succombez à la fraîcheur exotique de notre e-liquide au kiwi exquis. Chaque bouffée offre la saveur sucrée et acidulée du kiwi, pour une vape fruitée et vivifiante. </p>', 'http://127.0.0.1/em/pages/img-menu/menu-fruite.jpg', 'menu', ''),
(2, 'menu classique', 25, 'Menu contenant 10 eliquide de 10ml avec tout les gout de tabac possible et imaginable.', '<p class=\'p-eliquide\'> <b> 1. *Classic Doux :</b> Découvrez la subtilité du tabac avec notre e-liquide classic doux. Une saveur légère et délicate pour les amateurs de tabac nuancé. </p> <p class=\'p-eliquide\'> <b>2. *Classic Robuste : </b> Plongez dans l\'intensité avec notre e-liquide classic robuste. Des notes prononcées pour ceux qui préfèrent un goût de tabac plus fort. </p> <p class=\'p-eliquide\'> <b>3. *Classic American Blend : </b> Savourez l\'authenticité du tabac américain avec notre e-liquide American Blend. Une expérience riche et équilibrée qui rappelle les classiques du tabac. </p> <p class=\'p-eliquide\'> <b>4. *Classic Mentholé : </b> Une fusion rafraîchissante de tabac et de menthol. Notre e-liquide classic mentholé offre une touche glacée pour une expérience de vape revigorante. </p> <p class=\'p-eliquide\'> <b>5. *Classic Vanillé : </b> Découvrez l\'harmonie entre la douceur de la vanille et la richesse du tabac avec notre e-liquide classic vanillé. Une expérience subtile et crémeuse. </p> <p class=\'p-eliquide\'> <b>6. *Classic Noisette : </b> Un mariage parfait entre le tabac et la noisette. Notre e-liquide classic noisette offre une saveur unique et délicate pour une vape pleine de caractère. </p> <p class=\'p-eliquide\'> <b>7. *Classic Cognac : </b> Laissez-vous séduire par la sophistication de notre e-liquide classic cognac. Les nuances complexes du cognac se marient harmonieusement avec le tabac pour une expérience de vape élégante. </p> <p class=\'p-eliquide\'> <b>8. *Classic Expresso : </b> Éveillez vos sens avec notre e-liquide classic expresso. La fusion du tabac avec l\'arôme intense du café crée une expérience de vape robuste et énergisante. </p> <p class=\'p-eliquide\'> <b>9. *Classic Oriental : </b> Voyagez avec notre e-liquide classic oriental qui offre une expérience tabac inspirée des saveurs orientales, équilibrée et raffinée. </p> <p class=\'p-eliquide\'> <b>10. *Classic Naturel : </b> Appréciez la simplicité pure du tabac avec notre e-liquide classic naturel. Une expérience sans artifice pour les amateurs de saveurs authentiques. </p>', 'http://127.0.0.1/em/pages/img-menu/menu-classique.jpg', 'menu', ''),
(3, 'menu exotique', 18.99, 'Menu contenant 10 eliquide de 10ml qui vous feront voyager dans des destinations exotiques.', '<p class=\'p-eliquide\'> <b>1. *Mangue Passion : </b> Plongez dans l\'exotisme avec notre e-liquide mangue passion. L\'alliance sucrée de la mangue et de la passion crée une expérience fruitée intense. </p> <p class=\'p-eliquide\'> <b>2. *Ananas Coco : </b> Transportez-vous sur une plage tropicale avec notre e-liquide ananas coco. La douceur de l\'ananas se marie parfaitement à la saveur crémeuse de la noix de coco pour une vape exotique. </p> <p class=\'p-eliquide\'> <b>3. *Litchi Léger : </b> Découvrez la délicatesse du litchi avec notre e-liquide litchi léger. Une saveur subtile et sucrée pour une expérience exotique tout en légèreté. </p> <p class=\'p-eliquide\'> <b>4. *Fruit de la Passion : </b> Laissez-vous emporter par l\'intensité du fruit de la passion avec notre e-liquide dédié. Des notes acidulées et sucrées pour une vape exotique pleine de caractère. </p> <p class=\'p-eliquide\'> <b>5. *Goyave Guava : </b> Vivez une explosion de saveurs avec notre e-liquide goyave guava. La goyave rencontre la guava pour une expérience exotique équilibrée et délicieuse. </p> <p class=\'p-eliquide\'> <b>6. *Papaye Paradisiaque : </b> Succombez à la douceur de notre e-liquide papaye paradisiaque. La papaye offre une saveur sucrée et exotique, parfaite pour une vape tout en finesse. </p> <p class=\'p-eliquide\'> <b>7. *Cactus Citron Vert : </b> Explorez des saveurs uniques avec notre e-liquide cactus citron vert. L\'acidité du citron vert rencontre la fraîcheur du cactus pour une expérience exotique rafraîchissante. </p> <p class=\'p-eliquide\'> <b>8. *Banane Tropical : </b> Plongez dans la douceur de notre e-liquide banane tropical. La saveur sucrée et crémeuse de la banane s\'associe à d\'autres fruits tropicaux pour une vape exotique et délectable. </p> <p class=\'p-eliquide\'> <b>9. *Mélange de Baies Exotiques : </b> Plongez dans une symphonie de saveurs avec notre e-liquide mélange de baies exotiques. Un mélange unique de baies tropicales pour une vape fruitée et complexe. </p> <p class=\'p-eliquide\'> <b>10. *Fruit du Dragon Mystérieux : </b> Découvrez le mystère du fruit du dragon avec notre e-liquide fruit du dragon mystérieux. Une saveur exotique et sucrée pour une expérience de vape envoûtante. </p>', 'http://127.0.0.1/em/pages/img-menu/menu-exotique.jpg', 'menu', ''),
(4, 'menu gourmand', 19.99, 'Menu contenant 10 eliquide de 10ml qui vous donnera l\'impression d\'etre dans une patisserie.', '<p class=\'p-eliquide\'> <b>1. *Vanille Custard : </b> Plongez dans la richesse de notre e-liquide vanille custard. La douceur de la vanille associée à la crémosité de la custard crée une expérience gourmande et réconfortante. </p> <p class=\'p-eliquide\'> <b>2. *Caramel au Beurre Salé : </b> Succombez à la gourmandise avec notre e-liquide caramel au beurre salé. Les notes sucrées du caramel se mêlent à la délicatesse du beurre salé pour une vapeur indulgente. </p> <p class=\'p-eliquide\'> <b>3. *Chocolat Fondant : </b> Pour les amateurs de chocolat, notre e-liquide chocolat fondant offre une expérience riche et intense, avec des notes profondes de cacao pour une vapeur délicieuse. </p> <p class=\'p-eliquide\'> <b>4. *Cookies à la Vanille : </b> Dégustez l\'arôme réconfortant de nos cookies à la vanille. Notre e-liquide capture la saveur des cookies fraîchement sortis du four pour une vape gourmande et délicieuse. </p> <p class=\'p-eliquide\'> <b>5. *Tarte aux Pommes : </b> Plaisir automnal assuré avec notre e-liquide tarte aux pommes. La saveur sucrée des pommes cuites dans une pâte feuilletée crée une expérience gourmande équilibrée. </p> <p class=\'p-eliquide\'> <b>6. *Muffin aux Myrtilles : </b> Savourez la douceur de notre e-liquide muffin aux myrtilles. Les myrtilles juteuses s\'associent à la texture moelleuse du muffin pour une expérience gourmande et fruitée. </p> <p class=\'p-eliquide\'> <b>7. *Cappuccino Gourmand : </b> Éveillez vos sens avec notre e-liquide cappuccino gourmand. L\'alliance du café riche avec une pointe de crème offre une expérience gourmande et énergisante. </p> <p class=\'p-eliquide\'> <b>8. *Pudding au Caramel : </b> Plongez dans la douceur avec notre e-liquide pudding au caramel. La texture onctueuse du pudding se marie à la richesse du caramel pour une vape gourmande et succulente. </p> <p class=\'p-eliquide\'> <b>9. *Beignet à la Fraise : </b> Succombez à la tentation avec notre e-liquide beignet à la fraise. La douceur des fraises associée à la texture moelleuse du beignet crée une expérience gourmande et fruitée. </p> <p class=\'p-eliquide\'> <b>10. *Tiramisu Délicieux : </b> Terminez en beauté avec notre e-liquide tiramisu délicieux. Les couches de mascarpone, café et biscuits imbibés de liqueur offrent une vape gourmande et sophistiquée. </p>', 'http://127.0.0.1/em/pages/img-menu/menu-gourmand.jpg', 'menu', ''),
(5, 'menu menthole', 19.99, 'Menu contenant 10 eliquide de 10ml pour les plus givré d\'entre vous.', '<p class=\'p-eliquide\'> <b>1. *Menthe Fraîche: </b> Commencez avec la simplicité de notre e-liquide menthe fraîche. Une explosion de fraîcheur pure pour une expérience mentholée revitalisante. </p> <p class=\'p-eliquide\'> <b>2. *Menthe Glacée: </b> Plongez dans une vague de fraîcheur intense avec notre e-liquide menthe glacée. Des notes mentholées glacées qui laissent une sensation de fraîcheur durable. </p> <p class=\'p-eliquide\'> <b>3. *Menthe Verte Citron: </b> Éveillez vos papilles avec notre e-liquide menthe verte citron. L\'alliance rafraîchissante de la menthe verte et de l\'acidité du citron crée une expérience mentholée dynamique. </p> <p class=\'p-eliquide\'> <b>4. *Fruits des Bois Glacés: </b> Découvrez notre e-liquide fruits des bois glacés. Les fruits des bois rencontrent la fraîcheur mentholée pour une vapeur fruitée et revitalisante. </p> <p class=\'p-eliquide\'> <b>5. *Menthe Poivrée: </b> Explorez une saveur plus intense avec notre e-liquide menthe poivrée. La menthe poivrée offre une fraîcheur piquante pour une expérience mentholée stimulante. </p> <p class=\'p-eliquide\'> <b>6. *Mangue Menthol: </b> Plaisir exotique avec notre e-liquide mangue menthol. La douceur de la mangue associée à la fraîcheur du menthol crée une vapeur fruitée et mentholée. </p> <p class=\'p-eliquide\'> <b>7. *Menthe Chocolat: </b> Pour une expérience gourmande mentholée, notre e-liquide menthe chocolat associe la fraîcheur mentholée à la douceur du chocolat pour une vapeur délicieuse. </p> <p class=\'p-eliquide\'> <b>8. *Baies Rouges Glacées: </b> Profitez de la fraîcheur avec notre e-liquide baies rouges glacées. Les baies rouges rencontrent la menthe glacée pour une vape fruitée et mentholée. </p> <p class=\'p-eliquide\'> <b>9. *Pomme Verte Menthol: </b> Rafraîchissez-vous avec notre e-liquide pomme verte menthol. La saveur acidulée de la pomme verte combinée à la fraîcheur mentholée crée une expérience fruitée et revigorante. </p> <p class=\'p-eliquide\'> <b>10. *Citron Mentholé: </b> Terminez avec notre e-liquide citron mentholé. L\'acidité du citron associée à la fraîcheur mentholée offre une vapeur vive et mentholée. </p>', 'http://127.0.0.1/em/pages/img-menu/menu-menthole.jpg', 'menu', ''),
(6, 'red pearl', 11.99, 'E liquide Red Pearl en format 50ml pour plus de plaisir: des fraise, des oranges bien juteuses.', '', 'http://127.0.0.1/em/pages/img-eliquide/red-pearl-50ml.jpg', 'eliquide', ''),
(7, 'seven sins', 10.99, 'E liquide Seven Sins. Vos deux fruits jaunes préférés, en version givrée de 50ml !', 'Vos deux fruits jaunes préférés, en version givrée de 50ml ! D\'origine française et de qualité premium, le e-liquide Seven Sins 50ml reprend de savoureux fruits du verger frais, entre pêches et nectarines. Avec lui, vous goûterez l\'une des potions les plus fondantes du clan A&L Hidden Potion !', 'http://127.0.0.1/em/pages/img-eliquide/seven-sins-50ml.jpg', 'eliquide', ''),
(8, 'ragnarok', 9.99, 'E liquide Ragnarok Ultimate 50 ml. Une recette haute en couleur déjà bien connue, composée de fraises des bois, framboises, mûres et cassis.', '', 'http://127.0.0.1/em/pages/img-eliquide/ragnarok-50ml.jpg', 'eliquide', ''),
(9, 'shinigami', 9.99, 'E liquide Shinigami Ultimate 50 ml. Découvrez un mélange frais de pomme verte légèrement acidulée et d\'un bonbon intensément sucré.', 'Le célèbre bonbon bien frais à la pomme verte en e-liquide 50ml. Vous dégusterez de piquants bonbons à la pomme verte et profiterez de la célèbre fraicheur des Ultimate. Avec, toujours, une qualité premium, de fabrication 100% française, signée Arômes et Liquides !', 'http://127.0.0.1/em/pages/img-eliquide/shinigami-50ml.jpg', 'eliquide', ''),
(10, 'secret mango', 12.99, 'E liquide Secret Mango. Il est l\'heure de prendre votre potion pour garder la pêche.', '', 'http://127.0.0.1/em/pages/img-eliquide/secret-mango-50ml.jpg', 'eliquide', ''),
(11, 'shiva', 9.99, 'E liquide Shiva Ultimate 50 ml. Frissonnez de plaisir avec une menthe ultra fraiche et percutante !', 'Frissonnez de plaisir avec une menthe ultra fraiche et percutante ! Eliquide Ultimate 50 ml, boosté en arômes, proposé en flacon de 50 ml, avec une proportion de 50/50 en PG/VG et 0 mg/ml de nicotine. Pour obtenir 60 ml de votre e-liquide dosé en 3 mg/ml, ajoutez un booster de 10 ml en 20 mg/ml. Le e liquide Shiva 50 ml est produit en France par A&L', 'http://127.0.0.1/em/pages/img-eliquide/shiva-50ml.jpg', 'eliquide', ''),
(12, 'luxe q', 21.99, 'Vaporesso vous propose le Pod Luxe Q, une cigarette électronique conçue pour une vape au tirage restreint avec des cartouches dont la résistance est intégrée.', '', 'http://127.0.0.1/em/pages/img-ce/pod-luxe-q.jpg', 'ce', ''),
(13, 'drag x', 35.99, 'Le célèbre fabricant Voopoo qui a fait chavirer plusieurs de nos vapoteurs revient en force en ce début d\'année et s\'impose avec son élégante cigarette électronique Drag 4 !', '', 'http://127.0.0.1/em/pages/img-ce/pod-voopoo-drag-x-80w.jpg', 'ce', ''),
(14, 'aegis 200', 79.99, 'ce kit Aegis L200 Classic est le premier kit de Geekvape proposant une box Aegis (toujours étanche) fonctionnant avec deux accus 21700 ! La puissance, 200 watts, les performances et la vape en inhalation directe sont à l\'honneur.', '', 'http://127.0.0.1/em/pages/img-ce/aegis200.jpg', 'ce', ''),
(15, 'q16', 26.99, 'Le kit Q16 Pro de Justfog est idéal pour vapoter en toute simplicité et en toutes circonstances. Adapté à de nombreux types de e liquides, il offre une vape avec un tirage serré de grande qualité.', '', 'http://127.0.0.1/em/pages/img-ce/kit-q16-pro.jpg', 'ce', ''),
(16, 'novo 5', 21.99, 'Un nouveau design, un écran OLED de 0,69 pouces, une puissance réglable jusqu\'à 30W, un airflow réglable, le kit Novo 5 de Smoktech est un format pod compact et intuitif, pour le plus grand bonheur de tous les vapoteurs ! ', '', 'http://127.0.0.1/em/pages/img-ce/kit-novo-5-smoktech.jpg', 'ce', ''),
(17, 'gtx one', 27.99, 'Le kit GTX One de Vaporesso est une cigarette électronique pour les amateurs de vape en inhalation indirecte, avec un tirage plutôt serré. Il a été imaginé pour vapoter simplement, loin des complications. Il conviendra donc parfaitement à un vapoteur débutant.', '', 'http://127.0.0.1/em/pages/img-ce/kit-gtx-one-vaporesso.webp', 'ce', ''),
(18, 'drag 4', 65.99, 'la drag 4 Le célèbre fabricant Voopoo revient en force en ce début d\'année et s\'impose avec son élégante cigarette électronique Drag 4 !', '', 'http://127.0.0.1/em/pages/img-ce/drag-4.png', 'ce', ''),
(19, 'armour max', 59.99, 'Armour max Pour les vapoteurs qui ont besoin d\'une cigarette électronique solide qui ne craint rien, Vaporesso vous propose le kit Armour Max.', '', 'http://127.0.0.1/em/pages/img-ce/kit-armour-max-vaporesso.jpg', 'ce', ''),
(23, 'menu atypique', 23.99, 'Menu contenant 10 eliquide de 10ml qui vous donnera l\'impression d\'être dans une pâtisserie.', '<p class=\'p-eliquide\'> <b>1. Burger Barbecue : </b> Plongez dans l\'univers du fast-food avec notre e-liquide burger barbecue. Les saveurs fumées du barbecue associées à la tendreté de la viande créent une expérience gourmande unique. </p> <p class=\'p-eliquide\'> <b>2. Pizza Margherita : </b> Savourez l\'arôme de l\'Italie avec notre e-liquide pizza margherita. La saveur classique de la mozzarella, de la tomate et du basilic offre une expérience gourmande et délicieuse. </p> <p class=\'p-eliquide\'> <b>3. Chicken Wings Épicées : </b> Pour les amateurs de sensations fortes, notre e-liquide chicken wings épicées offre une expérience piquante et savoureuse, rappelant les ailes de poulet épicées d\'un fast-food. </p> <p class=\'p-eliquide\'> <b>4. Coca Cola Classique : </b> Rafraîchissez-vous avec notre e-liquide Coca Cola classique. La saveur emblématique de cette boisson gazeuse populaire pour une vape gourmande et pétillante. </p> <p class=\'p-eliquide\'> <b>5. Red Bull Tropical : </b> Énergisez-vous avec notre e-liquide Red Bull tropical. La saveur unique et pétillante de Red Bull associée à des notes tropicales offre une expérience gourmande et revigorante. </p> <p class=\'p-eliquide\'> <b>6. Cheeseburger Classique : </b> Retrouvez le goût du fast-food avec notre e-liquide cheeseburger classique. La fusion de la viande, du fromage, et des condiments offre une expérience gourmande fidèle à l\'original. </p> <p class=\'p-eliquide\'> <b>7. Milkshake à la Vanille : </b> Terminez votre repas avec notre e-liquide milkshake à la vanille. La crémosité de la vanille mélangée à la douceur du lait offre une vape gourmande et sucrée. </p> <p class=\'p-eliquide\'> <b>8. Café au Caramel : </b> Éveillez vos sens avec notre e-liquide café au caramel. L\'alliance du café robuste avec la douceur du caramel crée une expérience gourmande et énergisante. </p> <p class=\'p-eliquide\'> <b>9. Soda à la Cerise : </b> Rafraîchissez-vous avec notre e-liquide soda à la cerise. Les notes sucrées et pétillantes rappellent la boisson gazeuse classique à la cerise. </p> <p class=\'p-eliquide\'> <b>10. Sundae à la Fraise : </b> Finissez en douceur avec notre e-liquide sundae à la fraise. La fraîcheur des fraises associée à la texture onctueuse de la glace offre une vape gourmande et fruitée. </p>', 'http://127.0.0.1/em/pages/img-menu/menu-atypique.jpg', 'menu', ''),
(24, 'kami', 10.99, 'E liquide Kami Ultimate 50 ml. Un doux parfum d\'Orient avec ce mélange exotique et frais d\'une pitaya bien mûre et de fraises bien charnues.', '', 'http://127.0.0.1/em/pages/img-eliquide/kami-50ml.webp', 'eliquide', ''),
(25, 'bloody summer', 19.99, 'Une saveur de bonbon aux fruits rouges avec des notes de raisin et de cassis avec toujours cette touche de fraîcheur extrême ! All-day de nombreux vapoteurs, la saveur du Bloody Summer est le best seller de la gamme Fruizee !', '', 'http://127.0.0.1/em/pages/img-eliquide/bloody-summer-50ml.jpg', 'eliquide', ''),
(26, 'heisenberg', 18.89, 'Son nom fait bien sur référence à une célèbre série télé, le e liquide Heisenberg aux fruits rouges est reconnaissable entre tous grâce à sa couleur bleu.\r\n', '', 'http://127.0.0.1/em/pages/img-eliquide/heisenberg-50ml.jpg', 'eliquide', ''),
(27, 'blue devil', 15.99, 'Un e-liquide mystérieux, mais bel et bien fruité. Vous pourrez ressentir toute la puissance de la framboise bleue vous faire frétiller les papilles. Le cassis viendra à son tour ajouter une note légèrement acidulée à la recette. C\'est ensuite au tour de la menthe fraiche de venir glacer ce e-liquide avant d\'être adoucie par un généreux morceau de réglisse.', 'Framboise bleue, cassis ou encore menthe, voilà le trio gagnant de ce jus d\'exception. Mélangeant habilement le fruit avec les glaçons, la marque française AVAP vous présente son Blue Devil dans un grand format 50ml. Contenu dans un flacon de 60ml, vous pourrez facilement ajouter de la base neutre PG/VG ou encore un booster 10ml de nicotine. Pour vous aider dans la réalisation de votre recette, voici un petit guide :', 'http://127.0.0.1/em/pages/img-eliquide/blue-devil-50ml.jpg', 'eliquide', ''),
(28, 'valkyrie', 17.99, 'E liquide Valkyrie Ultimate 50 ml. Un assemblage juteux et sucré, il est composé de multiples fruits rouges avec une note plus importante de framboise bien charnue. Une recette bercée dans les bras d\'un monstre glacial qui vous apportera fraîcheur et tonus !', '', 'http://127.0.0.1/em/pages/img-eliquide/valkyrie-50ml.jpg', 'eliquide', ''),
(29, 'Argus GT2', 81.99, 'La marque Voopo revient avec une nouvelle version de son modèle Argus. Le Kit Argus GT2 Voopoo embarque deux accus (non fournis) pour une puissance maxi de 200W, ainsi qu’un clearomiseur Maat d’une contenance maximale de 6,5ml.', '', 'http://eliquide-menu.fr/pages/img-ce/gt2.jpg', 'ce', '');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
